target 'Swiftygram Example iOS' do
  use_frameworks!
  platform :ios, '9.0'
  
  pod 'Swiftygram', :path => '../'
end

#target 'Swiftygram Example macOS' do
#  platform :osx, '10.10'
#
#  pod 'Swiftygram', :path => '../'
#end
